import { useEffect, useState, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { IconButton, Button } from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import axios from 'axios';
import { useReactToPrint } from 'react-to-print';
import logo from './../../images/logo/logo.png';

function Window() {
  const { _id } = useParams();
  const [caseData, setCaseData] = useState(null);
  const [vehicleNum, setVehicleNumber] = useState('');
  const [detectionType, setDetectionType] = useState('');
  const [location, setLocation] = useState('');
  const [date, setDate] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const navigate = useNavigate();
  const componentPDF = useRef();

  useEffect(() => {
    if (_id) {
      axios.get(`http://localhost:8070/Detecto/CasesManage/moreinformation/${_id}`)
        .then(response => {
          setCaseData(response.data);
          setVehicleNumber(response.data.vehicalNum || ''); 
          setDetectionType(response.data.evidence || ''); 
          setLocation(response.data.location || '');
          setImageUrl(response.data.image || '');
          const rawDate = new Date(response.data.date);
          const formattedDate = `${rawDate.getFullYear()}-${('0' + (rawDate.getMonth() + 1)).slice(-2)}-${('0' + rawDate.getDate()).slice(-2)} ${('0' + rawDate.getHours()).slice(-2)}:${('0' + rawDate.getMinutes()).slice(-2)}`;
          setDate(formattedDate);
        })
        .catch(error => {
          console.error('Error fetching case data:', error);
        });
    }
  }, [_id]);

  const goBack = () => {
    navigate('/Dashboard/Cases');
  };

  const generatePDF = useReactToPrint({
    content: () => componentPDF.current,
  });

  const getCurrentDate = () => {
    const currentDate = new Date();
    return `${currentDate.getFullYear()}-${('0' + (currentDate.getMonth() + 1)).slice(-2)}-${('0' + currentDate.getDate()).slice(-2)} ${('0' + currentDate.getHours()).slice(-2)}:${('0' + currentDate.getMinutes()).slice(-2)}`;
  };

  return (
    <>
      <IconButton className="cursor-pointer" aria-label="back" onClick={goBack}>
        <ArrowBackIcon />
      </IconButton>
      <div ref={componentPDF}>
        <div className="grid grid-cols-2 gap-10">
          <h1 className="col-span-2 text-center" style={{ fontWeight: 'bold', fontSize: '45px' }}>General Report</h1>
  
          <div className="p-10">
            <img src={imageUrl} alt="Preview" style={{ width: '650px', height: '450px' }} />
          </div>
  
          <div className="p-15">
            {/* Right side content with white background */}
            <ul className="list-none p-0 m-0">
              <li className="flex mb-4">
                <label className="font-bold w-32">Case ID:</label>
                <span>{_id}</span>
              </li>
              <li className="flex mb-4">
                <label className="font-bold w-32">Vehicle Number:</label>
                <span>{vehicleNum}</span>
              </li>
              <li className="flex mb-4">
                <label className="font-bold w-32">Detection Type:</label>
                <span>{detectionType}</span>
              </li>
              <li className="flex mb-4">
                <label className="font-bold w-32">Location:</label>
                <span>{location}</span>
              </li>
              <li className="flex mb-4">
                <label className="font-bold w-32">Date:</label>
                <span>{date}</span>
              </li>
            </ul>
          </div>
        </div>

        <div className="flex flex-col items-center mt-4">
          <img src={logo} alt="Logo" style={{ width: '200px', height: '50px' }} />
          <p className="mt-2 text-center">Generated by Detecto System</p>
          <p className="mt-1 text-center">{getCurrentDate()}</p>
        </div>
      </div>
      <br />
      <div className="flex justify-center">
        <Button variant="contained" color="primary" onClick={generatePDF}>Generate Report</Button>
      </div>
      <br />
    </>
  );
}

export default Window;
